name: Build, Push, and Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-app .

      # Tag and push Docker image to ECR (replace with your ECR repo URI)
      - name: Tag and Push Docker image to Amazon ECR
        run: |
          ECR_REPO_URI="aws_account_id.dkr.ecr.region.amazonaws.com/flask-app"
          docker tag flask-app:latest $ECR_REPO_URI:latest
          docker push $ECR_REPO_URI:latest

      # Deploy to Amazon ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json  # Path to your ECS task definition file
          service: flask-app-service  # Replace with your ECS service name
          cluster: flask-app-cluster  # Replace with your ECS cluster name
          wait-for-service-stability: true  # Wait for the service to stabilize
